defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    TERM: dumb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: ./gradlew build --stacktrace
  release:
    <<: *defaults
    steps:
    - checkout
    - run: ./gradlew publishP2Repo -PbintrayUser=$BINTRAY_USER -PbintrayAPIKey=$BINTRAY_API_KEY
workflows:
  version: 2
  build:
    jobs:
    - build
  release-from-tag:
    jobs:
    - release:
        context: bintray-publish
        filters:
          tags:
            only: /^version-\d+\.\d+\.\d+$/
          branches:
            ignore: /.*/