<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gradle" nsURI="http://www.github.com/fraenkelc/buildship3_setuptask/1.0"
    nsPrefix="gradle">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="http://www.github.com/fraenkelc/buildship3_setuptask/schemas/Buildship3_setuptask-1.0.ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ImportGradleProjectTask" eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
      <details key="variableName" value="p2.import.gradle.project"/>
      <details key="repository" value="https://dl.bintray.com/fraenkelc/buildship3_setuptask/updates"/>
      <details key="installableUnits" value="com.github.fraenkelc.oomph.gradle.feature.group"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLocators" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/Resources.ecore#//SourceLocator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preSynchronizatonTasks"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
